services:
  mongo:
    image: mongo:7
    container_name: cinema_lab3_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    container_name: cinema_lab3_web
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: cinema_ticket_lab3

volumes:
  mongo_data:
